---
AWSTemplateFormatVersion: 2010-09-09
Description: The website configuration for 'jcleal.me'.

Parameters:
  Environment:
    Description: The environment used when deploying this service.
    Type: String

  Domain:
    Description: The domain registered.
    Type: String

  HostedZoneId:
    Description: The hosted zone id for the domain.
    Type: String

  AcmCertificateArn:
    Description: The certificate arn for the domain.
    Type: String

  LogBucket:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /common/distribution-logs-bucket

Conditions:
  CreateResources: !Equals [ !Ref "AWS::Region" , "ap-southeast-2" ]

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Condition: CreateResources
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref Domain
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
      AccessControl: BucketOwnerFullControl

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: CreateResources
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
          - Sid: allow-read-for-OAI
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt OriginAccessIdentity.S3CanonicalUserId
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${Bucket}/*"

  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub Access to ${Bucket}.

  Distribution:
    Type: AWS::CloudFront::Distribution
    Condition: CreateResources
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Ref Bucket
        Origins:
          - Id: S3Origin
            DomainName: !Sub "${Bucket}.s3.${AWS::Region}.amazonaws.com"
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${OriginAccessIdentity}
        HttpVersion: http2
        Aliases:
          - !Ref Bucket
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          Compress: true
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: true
          ViewerProtocolPolicy: redirect-to-https
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          SslSupportMethod: sni-only
        Logging:
          Bucket: !Sub "${LogBucket}.s3.amazonaws.com"
          Prefix: !Ref Bucket
          IncludeCookies: false

  RecordSet:
    Type: AWS::Route53::RecordSetGroup
    Condition: CreateResources
    DependsOn:
      - Distribution
    Properties:
      HostedZoneId: !Ref HostedZoneId
      RecordSets:
        - Name: !Ref Bucket
          Type: A
          AliasTarget:
            # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset-aliastarget.html
            HostedZoneId: Z2FDTNDATAQYW2 # must be this value for Cloudfront.
            DNSName: !GetAtt Distribution.DomainName

  BucketParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${Domain}/bucket
      Type: String
      Value: !Ref Bucket
