---
name: CI/CD
on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger]

jobs:
  lint:
    uses: jmpa-io/depot/.github/workflows/lint.yml@main
    secrets:
      github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

  deploy:
    uses: jmpa-io/depot/.github/workflows/deploy.yml@main

  sync:
    needs: [deploy]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout.
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Configure AWS.
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ap-southeast-2

      - name: Generate resume.
        run: ./bin/generate-resume.sh

      - name: Compile static website.
        run: ./bin/compile.sh

      - name: Sync to S3.
        run: ./bin/sync.sh

  post-to-slack:
    needs: [lint, sync]
    if: always()
    uses: jmpa-io/depot/.github/workflows/post-to-slack.yml@main
    secrets:
      github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
      slack-webhook: ${{ secrets.SLACK_GITHUB_WEBHOOK_URL }}
