---
name: CI/CD
on:
  push:
    paths:
    - '.github/workflows/cicd.yml'
    - 'cf/**'
    - 'cmd/**'
    - 'templates/**'
    - '**Dockerfile'
    - 'Makefile*'
  workflow_dispatch:
  repository_dispatch:
    types: [update-cicd]

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  lint:
    uses: jmpa-io/pipelines/.github/workflows/10-lint.yml@main
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_RUNNER_ROLE_NAME: ${{ secrets.AWS_RUNNER_ROLE_NAME }}
      ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}

  build-website:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout.
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Generate website.
        run: make generate-website

      - name: Upload artifact.
        uses: actions/upload-artifact@v4
        with:
          name: jcleal.me
          path: dist/public
          if-no-files-found: error
          retention-days: 7

  deploy:
    needs: [build-website]
    uses: jmpa-io/pipelines/.github/workflows/40-deploy.yml@main
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_RUNNER_ROLE_NAME: ${{ secrets.AWS_RUNNER_ROLE_NAME }}
      ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}

  upload-website:
    needs: [deploy, build-website]
    uses: jmpa-io/pipelines/.github/workflows/50-upload-artifacts-to-s3.yml@main
    with:
      artifact: jcleal.me
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_RUNNER_ROLE_NAME: ${{ secrets.AWS_RUNNER_ROLE_NAME }}

  post-to-slack:
    needs: [lint, build-website, deploy, upload-website]
    if: always()
    uses: jmpa-io/pipelines/.github/workflows/99-post-to-slack.yml@main
    secrets:
      WEBHOOK: ${{ secrets.SLACK_GITHUB_NOTIFICATIONS_WEBHOOK }}

